[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:asr_tts]
command=python3 asr_tts.py
directory=/root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/asr_tts.err.log
stdout_logfile=/var/log/supervisor/asr_tts.out.log
user=root

[program:asr_websocket]
command=python3 asr_websocket.py --host 0.0.0.0 --port 10095
directory=/root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/asr_websocket.err.log
stdout_logfile=/var/log/supervisor/asr_websocket.out.log
user=root

[program:tts_websocket]
command=python3 tts_websocket.py
directory=/root
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/tts_websocket.err.log
stdout_logfile=/var/log/supervisor/tts_websocket.out.log
user=root